# Generated by Django 2.2.4 on 2019-08-26 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rango_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
