# Generated by Django 2.2.4 on 2019-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango_core', '0002_remove_category_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
