# Generated by Django 2.2.4 on 2019-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango_core', '0002_auto_20190824_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
