# Generated by Django 2.2.4 on 2019-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [('rango_core', '0003_auto_20190826_2222'), ]

	operations = [migrations.AlterField(model_name='category', name='likes', field=models.IntegerField(default=0), ),
		migrations.AlterField(model_name='category', name='slug',
			field=models.SlugField(max_length=128, unique=True), ),
		migrations.AlterField(model_name='category', name='views', field=models.IntegerField(default=0), ), ]
