# Generated by Django 2.2.4 on 2019-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango_core', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
